docs/source/getting-started/installation.rst
grafana/default_grafana_dashboard.json

- updates the default workload number to display 0 if there are no GPUs scheduled
- fix typo in docs.

Dashboard updates

---

docs/source/conf.py

enables posthog monitoring for our readthedocs

add posthog

---

files/dcgm-metrics.csv
grafana/default_grafana_dashboard.json

Adds:
- disk
- sm efficiency
- sm occupancy
- nvlink counters
- infiniband counters
https://snapshots.raintank.io/dashboard/snapshot/aUOb6ZQzCheglWM84xTAvqwX4zQHTaUf?orgId=0

create default metrics exporter, add nvlink counters

---

manifests/kube-prometheus-stack.values

- Adds Infiniband hardware counters to `node-exporter`

add IB collector

---

docs/source/getting-started/installation.rst
docs/source/getting-started/observability.rst

- update links for grafana
- update gpu-operator docs for exporting SM metrics

update docs for enabling custom dcgm exports

---

docs/source/admin/installation.rst

fixes verbiage about the installed components.

update installation docs

---

docs/source/admin/installation.rst
docs/source/admin/observability.rst
docs/source/usage/quickstart.rst
grafana/default_grafana_dashboard.json
manifests/otel.values

This PR:
- adds a logging dashboard panel for pod error logs
- fixes disk usage gauge
- updates docs so helm releases don't have randomly generated release names
- point to `konduktor` branch of skypilot which we will maintain.

add logs dashboard panel, fixes disk usage gauge, update docs

---

grafana/default_grafana_dashboard.json
konduktor/manifests/dmesg_daemonset.yaml
manifests/README.md
pyproject.toml

creates a daemonset for pushing dmesg logs and adds a new dashboard for viewing errors found in dmesg

Dmesg logger

---

docs/source/admin/installation.rst
grafana/default_grafana_dashboard.json
konduktor/manifests/dmesg_daemonset.yaml
manifests/README.md
pyproject.toml

update docs to install daemonset for dmesg

Docs: Dmesg daemonset

---

.github/issue_template.md
.github/pull_request_template.md
.github/workflows/pypi-nightly-build.yaml
docs/source/admin/controller.rst
konduktor/__init__.py

this enables nightly builds of our package.

Build nightly

---

pyproject.toml

fixes packaging so nightlys can build and publish.

fix packaging

---

docs/source/admin/controller.rst
konduktor/manifests/controller_deployment.yaml

Adds a manifest and instructions for running the controller within the cluster instead of only outside the cluster.

add incluster controller deployment and docs

---

.github/workflows/lint.yaml
pyproject.toml

ruff format

---

docs/source/admin/controller.rst
docs/source/admin/installation.rst
docs/source/admin/observability.rst
docs/source/usage/quickstart.rst

Users no longer need to manually set datasources.
Also highlights important lines to run for quickstart and log lines for the controller.

[Docs] emphasize lines in docs, remove manual steps for observability

---

manifests/manifests.yaml

bumps kueue manifest to 0.8
Manually retested creation of Kueue on GKE
```
kubectl apply --server-side -f ./manifests/manifest.yaml
```

upgrade to kueue 0.8

---

docs/source/admin/installation.rst

Changed logger -> logging in docs so that kubectl get pods works

fixed logging typo

---

docs/source/usage/quickstart.rst

1. fixed repo to allow for new torch.distributed.launch --local-rank
2. fixed launch command to get nproc per node from skypilot rather than being hardcoded to 1

fixed repo and command for quickstart

---

README.md
docs/source/usage/quickstart.rst

Readme typo

---

grafana/default_grafana_dashboard.json

removes job names for mem util which didn't work on GKE for grafana.

fix selectors for memory gauge

---

docs/source/index.rst

[Docs] typo fix

---

.buildkite/pipeline.yaml

add trigger build to buildkite CI

---

docs/source/usage/quickstart.rst

[docs] Update quickstart.rst

---

docs/source/usage/quickstart.rst

[docs] patch

---

docs/source/usage/quickstart.rst
grafana/default_grafana_dashboard.json

Docs update

---

manifests/otel.values

adds toleration for `"cloud.google.com/gke-queued"` for `otel-collector` pods

[logging] dws tolerations

---

manifests/kube-prometheus-stack.values

This makes prometheus persist between updates and revisions. Still need to add backup to blob storage.

use pvc for prometheus

---

manifests/manifests.yaml

upgrades to kueue 0.9.0
```
kubectl apply -f manifests/manifests.yaml --server-side
```

upgrade to kueue 0.9.0

---

konduktor/dashboard/backend/sockets.py
manifests/bitnami-thanos.values

includes instructions for deploying thanos query

[prometheus] add optional thanos query

---

grafana/konduktor_user_gke.json

user dash on gke

---

grafana/konduktor_user_gke.json

show all workloads in timerange

---

manifests/otel.values

[otel] get pod labels
